CREATE TABLE ramsay_workforce.allocate.vwah_hoursassignment (
  RequiredGradeTypeExternalReference STRING COLLATE UTF8_BINARY,
  ResourcingUnitExternalReference STRING COLLATE UTF8_BINARY,
  CostCentreCode STRING COLLATE UTF8_BINARY,
  ResourcingUnitShortName STRING COLLATE UTF8_BINARY,
  NetHours BIGINT,
  PersonGradeExternalReference STRING COLLATE UTF8_BINARY,
  CancelReasonExternalReference INT,
  StaffNumber STRING COLLATE UTF8_BINARY,
  ResourcingUnitLongName STRING COLLATE UTF8_BINARY,
  Forenames STRING COLLATE UTF8_BINARY,
  ShiftType STRING COLLATE UTF8_BINARY,
  ValidDate STRING COLLATE UTF8_BINARY,
  Surname STRING COLLATE UTF8_BINARY,
  CancelReasonName INT,
  OwningUnitCode STRING COLLATE UTF8_BINARY,
  PersonGradeTypeCategoryName STRING COLLATE UTF8_BINARY,
  EmployeeTypeDescription STRING COLLATE UTF8_BINARY,
  HoursAssignmentID BIGINT,
  PostGradeLongName STRING COLLATE UTF8_BINARY,
  RequiredGradeTypeCategoryName STRING COLLATE UTF8_BINARY,
  ShiftStartDate STRING COLLATE UTF8_BINARY,
  ShiftEndDate STRING COLLATE UTF8_BINARY,
  CancelReasonDescription INT,
  FulfillmentStatusName STRING COLLATE UTF8_BINARY,
  ShiftName STRING COLLATE UTF8_BINARY,
  RequiredGradeTypeDescription STRING COLLATE UTF8_BINARY,
  EmployeeTypeName STRING COLLATE UTF8_BINARY,
  ActualStart STRING COLLATE UTF8_BINARY,
  ResourcingUnitCode STRING COLLATE UTF8_BINARY,
  OwningUnitLongName STRING COLLATE UTF8_BINARY,
  PayState STRING COLLATE UTF8_BINARY,
  PersonGradeTypeName STRING COLLATE UTF8_BINARY,
  WorkTime BIGINT,
  RequiredGradeTypeName STRING COLLATE UTF8_BINARY,
  RequiredGradeLongName STRING COLLATE UTF8_BINARY,
  WTE STRING COLLATE UTF8_BINARY,
  FulfillmentCategoryName STRING COLLATE UTF8_BINARY,
  AdditionalDutyReasonName STRING COLLATE UTF8_BINARY,
  OwningUnitShortName STRING COLLATE UTF8_BINARY,
  RequiredGradeExternalReference STRING COLLATE UTF8_BINARY,
  AssignmentMechanism STRING COLLATE UTF8_BINARY,
  CostCentreDescription STRING COLLATE UTF8_BINARY,
  PostGradeShortName STRING COLLATE UTF8_BINARY,
  PersonGradeShortName STRING COLLATE UTF8_BINARY,
  ActualLocationLongName STRING COLLATE UTF8_BINARY,
  EmployeeTypeExternalReference STRING COLLATE UTF8_BINARY,
  CostCentreName STRING COLLATE UTF8_BINARY,
  PostTitle STRING COLLATE UTF8_BINARY,
  RequiredGradeShortName STRING COLLATE UTF8_BINARY,
  OwningUnitExternalReference STRING COLLATE UTF8_BINARY,
  PersonGradeLongName STRING COLLATE UTF8_BINARY,
  PersonGradeTypeDescription STRING COLLATE UTF8_BINARY,
  FulfillmentTypeName STRING COLLATE UTF8_BINARY,
  AssignmentNumber STRING COLLATE UTF8_BINARY,
  CancelFlag BOOLEAN,
  ActualEnd STRING COLLATE UTF8_BINARY,
  WorkHours DOUBLE,
  ActualAgencyHours DOUBLE,
  ShiftState STRING COLLATE UTF8_BINARY,
  PlannedAgencyHours DOUBLE,
  SiteID STRING COLLATE UTF8_BINARY,
  SKeySiteMaster BIGINT,
  _rescued_data STRING COLLATE UTF8_BINARY)
USING delta
DEFAULT COLLATION UTF8_BINARY
TBLPROPERTIES (
  'delta.checkpoint.writeStatsAsJson' = 'false',
  'delta.checkpoint.writeStatsAsStruct' = 'true',
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.appendOnly' = 'supported',
  'delta.feature.deletionVectors' = 'supported',
  'delta.feature.invariants' = 'supported',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7',
  'delta.parquet.compression.codec' = 'zstd',
  'delta.parquet.format.version' = '2.12.0',
  'delta.parquet.format.version.afe.internal' = '2.12.0',
  'delta.workloadBasedColumns.deltaFileStatistics' = '`persongradeshortname`,`additionaldutyreasonname`,`siteid`,`plannedagencyhours`,`workhours`')
;
