CREATE TABLE ramsay_health.ops.tbinvoice (
  VisitID STRING COLLATE UTF8_BINARY,
  InvoiceValue BIGINT,
  CaseID STRING COLLATE UTF8_BINARY,
  SKeyBillVisit STRING COLLATE UTF8_BINARY,
  SiteID BIGINT,
  PatientID STRING COLLATE UTF8_BINARY,
  InvoiceNumber STRING COLLATE UTF8_BINARY,
  InvoiceType STRING COLLATE UTF8_BINARY,
  InvoiceCreatedDate STRING COLLATE UTF8_BINARY,
  InvoicePayor STRING COLLATE UTF8_BINARY,
  InvoicePayorCode STRING COLLATE UTF8_BINARY,
  InvoiceChannel STRING COLLATE UTF8_BINARY,
  PrimaryCCSDCode STRING COLLATE UTF8_BINARY,
  ProcedureDescription STRING COLLATE UTF8_BINARY,
  ProcedureGroup STRING COLLATE UTF8_BINARY,
  ComplexityCode STRING COLLATE UTF8_BINARY,
  ComplexityDescription STRING COLLATE UTF8_BINARY,
  HRGCode STRING COLLATE UTF8_BINARY,
  HRGDescription STRING COLLATE UTF8_BINARY,
  InvoiceContractCode STRING COLLATE UTF8_BINARY,
  InvoiceHospitalRevenue STRING COLLATE UTF8_BINARY,
  InvoiceCancelled STRING COLLATE UTF8_BINARY,
  IsCurrentInvoice STRING COLLATE UTF8_BINARY,
  BillPayorTaxonomyFlag BIGINT,
  OtherRevenue STRING COLLATE UTF8_BINARY,
  HighestValue BIGINT,
  AdmitCount BIGINT,
  AdmitOPCount BIGINT,
  LatestInvoiceCreatedDate BIGINT,
  MaxInvoiceNumber BIGINT)
USING delta
TBLPROPERTIES (
  'delta.checkpoint.writeStatsAsJson' = 'false',
  'delta.checkpoint.writeStatsAsStruct' = 'true',
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.appendOnly' = 'supported',
  'delta.feature.deletionVectors' = 'supported',
  'delta.feature.invariants' = 'supported',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7',
  'delta.parquet.compression.codec' = 'zstd',
  'delta.parquet.format.version' = '2.12.0',
  'delta.parquet.format.version.afe.internal' = '2.12.0',
  'delta.workloadBasedColumns.deltaFileStatistics' = '`invoicevalue`')
;
