CREATE TABLE ramsay_health.ops.tbreferrals (
  ReferralKey STRING COLLATE UTF8_BINARY,
  PatientKey STRING COLLATE UTF8_BINARY,
  HospitalKey DOUBLE,
  GPKey STRING COLLATE UTF8_BINARY,
  PracticeKey STRING COLLATE UTF8_BINARY,
  HCPKey STRING COLLATE UTF8_BINARY,
  JourneyKey STRING COLLATE UTF8_BINARY,
  ReferralSource STRING COLLATE UTF8_BINARY,
  ReferralID STRING COLLATE UTF8_BINARY,
  RegisteredGPID STRING COLLATE UTF8_BINARY,
  ReferralGPID STRING COLLATE UTF8_BINARY,
  ReferralRaisedDate STRING COLLATE UTF8_BINARY,
  ReferralReceivedDate STRING COLLATE UTF8_BINARY,
  ReferralAcceptedDate STRING COLLATE UTF8_BINARY,
  ReferralRejectedDate STRING COLLATE UTF8_BINARY,
  ReferralStatus STRING COLLATE UTF8_BINARY,
  ReferralCreatedBy STRING COLLATE UTF8_BINARY,
  ReferringICBCode STRING COLLATE UTF8_BINARY,
  ReferringICBName STRING COLLATE UTF8_BINARY,
  ServiceName STRING COLLATE UTF8_BINARY,
  PayorType STRING COLLATE UTF8_BINARY,
  TriageDate STRING COLLATE UTF8_BINARY,
  EndOfTreatmentDate STRING COLLATE UTF8_BINARY,
  ReferralUrgency STRING COLLATE UTF8_BINARY,
  UBRN STRING COLLATE UTF8_BINARY,
  ReferrerName STRING COLLATE UTF8_BINARY,
  IsProviderCancelled BIGINT,
  AgeAtDateOfReferral BIGINT,
  ERSFlag BIGINT,
  FirstApptDate STRING COLLATE UTF8_BINARY,
  AdmissionCount STRING COLLATE UTF8_BINARY,
  BookingCount BIGINT,
  HasAdmission BIGINT,
  HasBooking BIGINT,
  HasVisit BIGINT,
  DaycaseCount STRING COLLATE UTF8_BINARY,
  InpatientCount STRING COLLATE UTF8_BINARY,
  OutpatientCount BIGINT,
  PayorContractKey DOUBLE)
USING delta
TBLPROPERTIES (
  'delta.checkpoint.writeStatsAsJson' = 'false',
  'delta.checkpoint.writeStatsAsStruct' = 'true',
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.appendOnly' = 'supported',
  'delta.feature.deletionVectors' = 'supported',
  'delta.feature.invariants' = 'supported',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7',
  'delta.parquet.compression.codec' = 'zstd',
  'delta.parquet.format.version' = '2.12.0',
  'delta.parquet.format.version.afe.internal' = '2.12.0',
  'delta.workloadBasedColumns.deltaFileStatistics' = '`hasadmission`')
;
