CREATE TABLE ramsay_health.ops.vwah_unavailability (
  DutyEndTime STRING COLLATE UTF8_BINARY,
  UnavailabilityState STRING COLLATE UTF8_BINARY,
  ReferToOccHealth BIGINT,
  ReturnToWorkInterviewComplete BIGINT,
  UnavailabilityReason STRING COLLATE UTF8_BINARY,
  StaffNumber STRING COLLATE UTF8_BINARY,
  SecondarySicknessReason STRING COLLATE UTF8_BINARY,
  Forenames STRING COLLATE UTF8_BINARY,
  ValidDate STRING COLLATE UTF8_BINARY,
  Surname INT,
  PostCode STRING COLLATE UTF8_BINARY,
  HoursAssignmentID STRING COLLATE UTF8_BINARY,
  PostGradeLongName STRING COLLATE UTF8_BINARY,
  FromRequest STRING COLLATE UTF8_BINARY,
  UnavailabilityTime BIGINT,
  UnavailabilityEndDate STRING COLLATE UTF8_BINARY,
  OccHealthReferalDate STRING COLLATE UTF8_BINARY,
  EmployeeTypeName STRING COLLATE UTF8_BINARY,
  WORKMINUTESMISSED BIGINT,
  UnavailabilityStartDate STRING COLLATE UTF8_BINARY,
  OwningUnitLongName STRING COLLATE UTF8_BINARY,
  OwningUnitShortName STRING COLLATE UTF8_BINARY,
  UnavailabilityReasonGroup STRING COLLATE UTF8_BINARY,
  AssignmentMechanism STRING COLLATE UTF8_BINARY,
  PostGradeShortName STRING COLLATE UTF8_BINARY,
  PersonGradeShortName STRING COLLATE UTF8_BINARY,
  UnavailabilityHasWarnings BIGINT,
  DutyStartTime STRING COLLATE UTF8_BINARY,
  PostTitle STRING COLLATE UTF8_BINARY,
  Paystate STRING COLLATE UTF8_BINARY,
  PersonGradeTypeShortName STRING COLLATE UTF8_BINARY,
  ReturnToWorkInterviewDate STRING COLLATE UTF8_BINARY,
  AssignmentNumber STRING COLLATE UTF8_BINARY,
  DeletedFlag INT,
  SicknessHours DOUBLE,
  AnnualLeaveHours DOUBLE,
  LostHours DOUBLE,
  EmployeeID STRING COLLATE UTF8_BINARY,
  CostCentreCode STRING COLLATE UTF8_BINARY,
  SiteID STRING COLLATE UTF8_BINARY,
  SKeySiteMaster STRING COLLATE UTF8_BINARY,
  PERSONNONEFFECTIVEPERIODID STRING COLLATE UTF8_BINARY)
USING delta
DEFAULT COLLATION UTF8_BINARY
TBLPROPERTIES (
  'delta.checkpoint.writeStatsAsJson' = 'false',
  'delta.checkpoint.writeStatsAsStruct' = 'true',
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.appendOnly' = 'supported',
  'delta.feature.deletionVectors' = 'supported',
  'delta.feature.invariants' = 'supported',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7',
  'delta.parquet.compression.codec' = 'zstd',
  'delta.parquet.format.version' = '2.12.0',
  'delta.parquet.format.version.afe.internal' = '2.12.0',
  'delta.workloadBasedColumns.deltaFileStatistics' = '`losthours`')
;
